### ISSUE TITLE
Encoding and Decoding messages that include service definitions

### ISSUE THREAD

**Issue by mmmries** [bitwalker/exprotobuf#16]
Similar to #15 if I try to define a message that includes a service definition I get an `CaseClauseError`.

Reproducible test:

```elixir
defmodule ServiceDefinitionsTest do
  use ExUnit.Case

  defmodule Proto do
    use Protobuf, """
      message Msg {
        optional string name = 1;
      }
      service MsgService {
        rpc Create (Msg) returns (Msg);
      }
    """
  end

  test "it can create an extended message" do
    msg = Proto.Msg.new(name: "Ron")
    assert msg == %Proto.Msg{name: "Ron"}
  end

  test "it can encode an extended message" do
    msg = Proto.Msg.new(name: "Ron")
    assert Proto.Msg.encode(msg) == <<10, 3, 82, 111, 110>>
  end

  test "it can decode an extended message" do
    encoded = <<10, 3, 82, 111, 110>>
    assert Proto.Msg.decode(encoded) == %Proto.Msg{name: "Ron"}
  end
end
```

I get these results

```
.

  1) test it can decode an extended message (ExtensionFieldTest)
     test/rpc_definitions_test.exs:25
     ** (CaseClauseError) no case clause matching: :service
     stacktrace:
       lib/exprotobuf/decoder.ex:9: anonymous fn/2 in Protobuf.Decoder.decode/2
       (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
       lib/exprotobuf/decoder.ex:8: Protobuf.Decoder.decode/2
       test/rpc_definitions_test.exs:27



  2) test it can encode an extended message (ExtensionFieldTest)
     test/rpc_definitions_test.exs:20
     ** (CaseClauseError) no case clause matching: :service
     stacktrace:
       lib/exprotobuf/encoder.ex:7: anonymous fn/2 in Protobuf.Encoder.encode/2
       (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
       lib/exprotobuf/encoder.ex:6: Protobuf.Encoder.encode/2
       test/rpc_definitions_test.exs:22



Finished in 0.1 seconds (0.1s on load, 0.00s on tests)
3 tests, 2 failures

Randomized with seed 298949
```

**Comment by bitwalker** [comment]
It looks like we can get the service defs from :gpb, so this one we can add to the TODO after extensions.

**Comment by mmmries** [comment]
I was just about to start working on this tonight, but I realized that it is already supported. Something like this works now:

```elixir
defmodule Message do
  use Protobuf, """
    message Greeting {
      optional string name = 1;
    }
    service HelloService {
      rpc hello(Greeting) returns (Greeting);
    }
  """
end
```

Then at runtime I can do:
```
iex(6)> Message.defs
[{{:msg, Message.Greeting},
  [%Protobuf.Field{fnum: 1, name: :name, occurrence: :optional, opts: [],
    rnum: 2, type: :string}]},
 {{:service, Message.HelloService}, [{:rpc, :hello, :Greeting, :Greeting}]}]
```

This gives me the ability to reflect on all my protobuf service definitions and see their respective types. Woohoo! Thanks @bitwalker

**Comment by bitwalker** [comment]
I hadn't revisited this since some recent changes were merged, I'm glad this is resolved already!
