### ISSUE TITLE
Oneof support

### ISSUE THREAD

**Issue by kwojtaszek** [bitwalker/exprotobuf#20]
It looks like oneof feature of protobuf isn't supported by exprotobuf and causes compilation error.

Here's example proto file:
```
package chat;

option java_package = "com.appunite.chat";

// From server to client
message WebsocketServerContainer {
  oneof response {
      int32 create_conversation = 1;
      int32 create_single_conversation_confirmation = 2;
      int32 create_group_conversation_confirmation = 3;
    }
}
```

that cases problem during compilation:
```
== Compilation error on file web/models/chat_protocol.ex ==
** (ArgumentError) argument error
    lib/exprotobuf/utils.ex:32: anonymous fn/3 in Protobuf.Utils.convert_from_record/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/exprotobuf.ex:78: Protobuf.namespace_fields/2
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    lib/exprotobuf.ex:69: anonymous fn/4 in Protobuf.namespace_types/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by kwojtaszek** [comment]
@bitwalker pull request with oneof fields support is ready for review

**Comment by rafal-radziszewski** [comment]
@bitwalker We added some fixes to style and simplified some parts, take a look at it when you can.

**Comment by bitwalker** [comment]
@kwojtaszek @rafal-radziszewski I've made some comments, then we just need to squash the commits and I can merge it :+1:

**Comment by kwojtaszek** [comment]
closing
