### ISSUE TITLE
Support "reserved field"

### ISSUE THREAD

**Issue by rm1138** [bitwalker/exprotobuf#81]

**Comment by vlarok** [comment]
Hi, I have the same problem. Seems it not supported yet.  Please help.
Field
reserved 6;
--------exprotobuf---
defmodule Protobuf.Encoder do
  alias Protobuf.Utils
  alias Protobuf.Field
  alias Protobuf.OneOfField

  def encode(%{} = msg, defs) do
    fixed_defs = for {{type, mod}, fields} <- defs, into: [] do
      {{type, mod}, fields} |> IO.inspect

------IO.Inspect----
{{:msg, Worker.Protobuf.Message}, [6]}

------stacktrace----
 (exprotobuf) lib/exprotobuf/encoder.ex:11: anonymous fn/1 in Protobuf.Encoder.encode/2
       (elixir) lib/enum.ex:1286: Enum."-map/2-lists^map/1-0-"/2
       (exprotobuf) lib/exprotobuf/encoder.ex:10: anonymous fn/2 in Protobuf.Encoder.encode/2
       (elixir) lib/enum.ex:1891: Enum."-reduce/3-lists^foldl/2-0-"/3
       (exprotobuf) lib/exprotobuf/encoder.ex:7: Protobuf.Encoder.encode/2
       test/transaction/consumer_test.exs:39: Worker.ConsumerTest.start_amqp_publish/0
       test/transaction/consumer_test.exs:1: Worker.ConsumerTest.__ex_unit__/2

**Comment by mingchuno** [comment]
@bitwalker any idea?

**Comment by cheng81** [comment]
I have the same problem!

**Comment by cheng81** [comment]
@bitwalker I made a PR #111 to solve this issue
